# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = /usr/local

bindir = /usr/local/games
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = /usr/local/share/games/openglad
sysconfdir = /usr/local/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/openglad
pkglibdir = $(libdir)/openglad
pkgincludedir = $(includedir)/openglad
top_builddir = ..

ACLOCAL = ${SHELL} /home/sark/Desktop/android_libs/games/openglad-0.98/missing --run aclocal
AUTOCONF = ${SHELL} /home/sark/Desktop/android_libs/games/openglad-0.98/missing --run autoconf
AUTOMAKE = ${SHELL} /home/sark/Desktop/android_libs/games/openglad-0.98/missing --run automake
AUTOHEADER = ${SHELL} /home/sark/Desktop/android_libs/games/openglad-0.98/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
AMTAR = ${SHELL} /home/sark/Desktop/android_libs/games/openglad-0.98/missing --run tar
AWK = gawk
CC = gcc
CXX = g++
DEPDIR = .deps
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
OBJEXT = o
PACKAGE = openglad
SDL_CFLAGS = -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDL_CONFIG = /usr/bin/sdl-config
SDL_LIBS = -lSDL -lpthread
VERSION = 0.98
am__include = include
am__quote = 
install_sh = /home/sark/Desktop/android_libs/games/openglad-0.98/install-sh

bin_PROGRAMS = openglad openscen

#EXTRA_PROGRAMS = openscen
openglad_SOURCES = glad.cpp button.cpp effect.cpp game.cpp gladpack.cpp \
graphlib.cpp guy.cpp help.cpp input.cpp intro.cpp living.cpp loader.cpp \
obmap.cpp pal32.cpp parser.cpp picker.cpp pixie.cpp pixien.cpp radar.cpp \
screen.cpp smooth.cpp sound.cpp stats.cpp text.cpp treasure.cpp video.cpp \
view.cpp walker.cpp weap.cpp sai2x.cpp util.cpp\
base.h button.h colors.h effect.h gladpack.h graph.h guy.h input.h living.h \
loader.h obmap.h pal32.h palettes.h parser.h picker.h pixdefs.h pixie.h \
pixien.h radar.h scen.h screen.h smooth.h soundob.h sounds.h stats.h text.h \
treasure.h video.h view.h walker.h weap.h sai2x.h util.h


openscen_SOURCES = scen.cpp effect.cpp game.cpp gladpack.cpp \
graphlib.cpp guy.cpp help.cpp input.cpp intro.cpp living.cpp loader.cpp \
obmap.cpp pal32.cpp parser.cpp pixie.cpp pixien.cpp radar.cpp \
screen.cpp smooth.cpp sound.cpp stats.cpp text.cpp treasure.cpp video.cpp \
view.cpp walker.cpp weap.cpp sai2x.cpp util.cpp\
base.h colors.h effect.h gladpack.h graph.h guy.h input.h living.h \
loader.h obmap.h pal32.h palettes.h parser.h pixdefs.h pixie.h \
pixien.h radar.h scen.h screen.h smooth.h soundob.h sounds.h stats.h text.h \
treasure.h video.h view.h walker.h weap.h sai2x.h util.h

openscen_CXXFLAGS = -DOPENSCEN
subdir = src
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
bin_PROGRAMS = openglad$(EXEEXT) openscen$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am_openglad_OBJECTS = glad.$(OBJEXT) button.$(OBJEXT) effect.$(OBJEXT) \
	game.$(OBJEXT) gladpack.$(OBJEXT) graphlib.$(OBJEXT) \
	guy.$(OBJEXT) help.$(OBJEXT) input.$(OBJEXT) intro.$(OBJEXT) \
	living.$(OBJEXT) loader.$(OBJEXT) obmap.$(OBJEXT) \
	pal32.$(OBJEXT) parser.$(OBJEXT) picker.$(OBJEXT) \
	pixie.$(OBJEXT) pixien.$(OBJEXT) radar.$(OBJEXT) \
	screen.$(OBJEXT) smooth.$(OBJEXT) sound.$(OBJEXT) \
	stats.$(OBJEXT) text.$(OBJEXT) treasure.$(OBJEXT) \
	video.$(OBJEXT) view.$(OBJEXT) walker.$(OBJEXT) weap.$(OBJEXT) \
	sai2x.$(OBJEXT) util.$(OBJEXT)
openglad_OBJECTS = $(am_openglad_OBJECTS)
openglad_LDADD = $(LDADD)
openglad_DEPENDENCIES =
openglad_LDFLAGS =
am_openscen_OBJECTS = openscen-scen.$(OBJEXT) openscen-effect.$(OBJEXT) \
	openscen-game.$(OBJEXT) openscen-gladpack.$(OBJEXT) \
	openscen-graphlib.$(OBJEXT) openscen-guy.$(OBJEXT) \
	openscen-help.$(OBJEXT) openscen-input.$(OBJEXT) \
	openscen-intro.$(OBJEXT) openscen-living.$(OBJEXT) \
	openscen-loader.$(OBJEXT) openscen-obmap.$(OBJEXT) \
	openscen-pal32.$(OBJEXT) openscen-parser.$(OBJEXT) \
	openscen-pixie.$(OBJEXT) openscen-pixien.$(OBJEXT) \
	openscen-radar.$(OBJEXT) openscen-screen.$(OBJEXT) \
	openscen-smooth.$(OBJEXT) openscen-sound.$(OBJEXT) \
	openscen-stats.$(OBJEXT) openscen-text.$(OBJEXT) \
	openscen-treasure.$(OBJEXT) openscen-video.$(OBJEXT) \
	openscen-view.$(OBJEXT) openscen-walker.$(OBJEXT) \
	openscen-weap.$(OBJEXT) openscen-sai2x.$(OBJEXT) \
	openscen-util.$(OBJEXT)
openscen_OBJECTS = $(am_openscen_OBJECTS)
openscen_LDADD = $(LDADD)
openscen_DEPENDENCIES =
openscen_LDFLAGS =

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I.
CPPFLAGS = 
LDFLAGS = 
LIBS =  -lSDL -lpthread
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/button.Po $(DEPDIR)/effect.Po \
	$(DEPDIR)/game.Po $(DEPDIR)/glad.Po \
	$(DEPDIR)/gladpack.Po $(DEPDIR)/graphlib.Po \
	$(DEPDIR)/guy.Po $(DEPDIR)/help.Po \
	$(DEPDIR)/input.Po $(DEPDIR)/intro.Po \
	$(DEPDIR)/living.Po $(DEPDIR)/loader.Po \
	$(DEPDIR)/obmap.Po $(DEPDIR)/openscen-effect.Po \
	$(DEPDIR)/openscen-game.Po \
	$(DEPDIR)/openscen-gladpack.Po \
	$(DEPDIR)/openscen-graphlib.Po \
	$(DEPDIR)/openscen-guy.Po \
	$(DEPDIR)/openscen-help.Po \
	$(DEPDIR)/openscen-input.Po \
	$(DEPDIR)/openscen-intro.Po \
	$(DEPDIR)/openscen-living.Po \
	$(DEPDIR)/openscen-loader.Po \
	$(DEPDIR)/openscen-obmap.Po \
	$(DEPDIR)/openscen-pal32.Po \
	$(DEPDIR)/openscen-parser.Po \
	$(DEPDIR)/openscen-pixie.Po \
	$(DEPDIR)/openscen-pixien.Po \
	$(DEPDIR)/openscen-radar.Po \
	$(DEPDIR)/openscen-sai2x.Po \
	$(DEPDIR)/openscen-scen.Po \
	$(DEPDIR)/openscen-screen.Po \
	$(DEPDIR)/openscen-smooth.Po \
	$(DEPDIR)/openscen-sound.Po \
	$(DEPDIR)/openscen-stats.Po \
	$(DEPDIR)/openscen-text.Po \
	$(DEPDIR)/openscen-treasure.Po \
	$(DEPDIR)/openscen-util.Po \
	$(DEPDIR)/openscen-video.Po \
	$(DEPDIR)/openscen-view.Po \
	$(DEPDIR)/openscen-walker.Po \
	$(DEPDIR)/openscen-weap.Po $(DEPDIR)/pal32.Po \
	$(DEPDIR)/parser.Po $(DEPDIR)/picker.Po \
	$(DEPDIR)/pixie.Po $(DEPDIR)/pixien.Po \
	$(DEPDIR)/radar.Po $(DEPDIR)/sai2x.Po \
	$(DEPDIR)/screen.Po $(DEPDIR)/smooth.Po \
	$(DEPDIR)/sound.Po $(DEPDIR)/stats.Po \
	$(DEPDIR)/text.Po $(DEPDIR)/treasure.Po \
	$(DEPDIR)/util.Po $(DEPDIR)/video.Po \
	$(DEPDIR)/view.Po $(DEPDIR)/walker.Po \
	$(DEPDIR)/weap.Po
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
CXXFLAGS = -g -O2 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
CFLAGS = -g -O2
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES = $(openglad_SOURCES) $(openscen_SOURCES)
DIST_COMMON = ./stamp-h.in Makefile.am Makefile.in config.h.in
SOURCES = $(openglad_SOURCES) $(openscen_SOURCES)

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.ac $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  src/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
config.h: stamp-h
	@if test ! -f $@; then \
		rm -f stamp-h; \
		$(MAKE) stamp-h; \
	else :; fi
stamp-h: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h stamp-hT
	@echo timestamp > stamp-hT 2> /dev/null
	cd $(top_builddir) \
	  && CONFIG_FILES= CONFIG_HEADERS=src/config.h \
	     $(SHELL) ./config.status
	@mv stamp-hT stamp-h
$(srcdir)/config.h.in:  $(srcdir)/./stamp-h.in
	@if test ! -f $@; then \
		rm -f $(srcdir)/./stamp-h.in; \
		$(MAKE) $(srcdir)/./stamp-h.in; \
	else :; fi
$(srcdir)/./stamp-h.in: $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
	@rm -f $(srcdir)/./stamp-h.in $(srcdir)/./stamp-h.inT
	@echo timestamp > $(srcdir)/./stamp-h.inT 2> /dev/null
	cd $(top_srcdir) && $(AUTOHEADER)
	@mv $(srcdir)/./stamp-h.inT $(srcdir)/./stamp-h.in

distclean-hdr:
	-rm -f config.h
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo $$p1|sed '$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
openglad$(EXEEXT): $(openglad_OBJECTS) $(openglad_DEPENDENCIES) 
	@rm -f openglad$(EXEEXT)
	$(CXXLINK) $(openglad_LDFLAGS) $(openglad_OBJECTS) $(openglad_LDADD) $(LIBS)
openscen-scen.$(OBJEXT): scen.cpp
openscen-effect.$(OBJEXT): effect.cpp
openscen-game.$(OBJEXT): game.cpp
openscen-gladpack.$(OBJEXT): gladpack.cpp
openscen-graphlib.$(OBJEXT): graphlib.cpp
openscen-guy.$(OBJEXT): guy.cpp
openscen-help.$(OBJEXT): help.cpp
openscen-input.$(OBJEXT): input.cpp
openscen-intro.$(OBJEXT): intro.cpp
openscen-living.$(OBJEXT): living.cpp
openscen-loader.$(OBJEXT): loader.cpp
openscen-obmap.$(OBJEXT): obmap.cpp
openscen-pal32.$(OBJEXT): pal32.cpp
openscen-parser.$(OBJEXT): parser.cpp
openscen-pixie.$(OBJEXT): pixie.cpp
openscen-pixien.$(OBJEXT): pixien.cpp
openscen-radar.$(OBJEXT): radar.cpp
openscen-screen.$(OBJEXT): screen.cpp
openscen-smooth.$(OBJEXT): smooth.cpp
openscen-sound.$(OBJEXT): sound.cpp
openscen-stats.$(OBJEXT): stats.cpp
openscen-text.$(OBJEXT): text.cpp
openscen-treasure.$(OBJEXT): treasure.cpp
openscen-video.$(OBJEXT): video.cpp
openscen-view.$(OBJEXT): view.cpp
openscen-walker.$(OBJEXT): walker.cpp
openscen-weap.$(OBJEXT): weap.cpp
openscen-sai2x.$(OBJEXT): sai2x.cpp
openscen-util.$(OBJEXT): util.cpp
openscen$(EXEEXT): $(openscen_OBJECTS) $(openscen_DEPENDENCIES) 
	@rm -f openscen$(EXEEXT)
	$(CXXLINK) $(openscen_LDFLAGS) $(openscen_OBJECTS) $(openscen_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/button.Po
include $(DEPDIR)/effect.Po
include $(DEPDIR)/game.Po
include $(DEPDIR)/glad.Po
include $(DEPDIR)/gladpack.Po
include $(DEPDIR)/graphlib.Po
include $(DEPDIR)/guy.Po
include $(DEPDIR)/help.Po
include $(DEPDIR)/input.Po
include $(DEPDIR)/intro.Po
include $(DEPDIR)/living.Po
include $(DEPDIR)/loader.Po
include $(DEPDIR)/obmap.Po
include $(DEPDIR)/openscen-effect.Po
include $(DEPDIR)/openscen-game.Po
include $(DEPDIR)/openscen-gladpack.Po
include $(DEPDIR)/openscen-graphlib.Po
include $(DEPDIR)/openscen-guy.Po
include $(DEPDIR)/openscen-help.Po
include $(DEPDIR)/openscen-input.Po
include $(DEPDIR)/openscen-intro.Po
include $(DEPDIR)/openscen-living.Po
include $(DEPDIR)/openscen-loader.Po
include $(DEPDIR)/openscen-obmap.Po
include $(DEPDIR)/openscen-pal32.Po
include $(DEPDIR)/openscen-parser.Po
include $(DEPDIR)/openscen-pixie.Po
include $(DEPDIR)/openscen-pixien.Po
include $(DEPDIR)/openscen-radar.Po
include $(DEPDIR)/openscen-sai2x.Po
include $(DEPDIR)/openscen-scen.Po
include $(DEPDIR)/openscen-screen.Po
include $(DEPDIR)/openscen-smooth.Po
include $(DEPDIR)/openscen-sound.Po
include $(DEPDIR)/openscen-stats.Po
include $(DEPDIR)/openscen-text.Po
include $(DEPDIR)/openscen-treasure.Po
include $(DEPDIR)/openscen-util.Po
include $(DEPDIR)/openscen-video.Po
include $(DEPDIR)/openscen-view.Po
include $(DEPDIR)/openscen-walker.Po
include $(DEPDIR)/openscen-weap.Po
include $(DEPDIR)/pal32.Po
include $(DEPDIR)/parser.Po
include $(DEPDIR)/picker.Po
include $(DEPDIR)/pixie.Po
include $(DEPDIR)/pixien.Po
include $(DEPDIR)/radar.Po
include $(DEPDIR)/sai2x.Po
include $(DEPDIR)/screen.Po
include $(DEPDIR)/smooth.Po
include $(DEPDIR)/sound.Po
include $(DEPDIR)/stats.Po
include $(DEPDIR)/text.Po
include $(DEPDIR)/treasure.Po
include $(DEPDIR)/util.Po
include $(DEPDIR)/video.Po
include $(DEPDIR)/view.Po
include $(DEPDIR)/walker.Po
include $(DEPDIR)/weap.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.cpp.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cpp.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`

openscen-scen.o: scen.cpp
	source='scen.cpp' object='openscen-scen.o' libtool=no \
	depfile='$(DEPDIR)/openscen-scen.Po' tmpdepfile='$(DEPDIR)/openscen-scen.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-scen.o `test -f scen.cpp || echo '$(srcdir)/'`scen.cpp

openscen-scen.obj: scen.cpp
	source='scen.cpp' object='openscen-scen.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-scen.Po' tmpdepfile='$(DEPDIR)/openscen-scen.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-scen.obj `cygpath -w scen.cpp`

openscen-effect.o: effect.cpp
	source='effect.cpp' object='openscen-effect.o' libtool=no \
	depfile='$(DEPDIR)/openscen-effect.Po' tmpdepfile='$(DEPDIR)/openscen-effect.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-effect.o `test -f effect.cpp || echo '$(srcdir)/'`effect.cpp

openscen-effect.obj: effect.cpp
	source='effect.cpp' object='openscen-effect.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-effect.Po' tmpdepfile='$(DEPDIR)/openscen-effect.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-effect.obj `cygpath -w effect.cpp`

openscen-game.o: game.cpp
	source='game.cpp' object='openscen-game.o' libtool=no \
	depfile='$(DEPDIR)/openscen-game.Po' tmpdepfile='$(DEPDIR)/openscen-game.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-game.o `test -f game.cpp || echo '$(srcdir)/'`game.cpp

openscen-game.obj: game.cpp
	source='game.cpp' object='openscen-game.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-game.Po' tmpdepfile='$(DEPDIR)/openscen-game.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-game.obj `cygpath -w game.cpp`

openscen-gladpack.o: gladpack.cpp
	source='gladpack.cpp' object='openscen-gladpack.o' libtool=no \
	depfile='$(DEPDIR)/openscen-gladpack.Po' tmpdepfile='$(DEPDIR)/openscen-gladpack.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-gladpack.o `test -f gladpack.cpp || echo '$(srcdir)/'`gladpack.cpp

openscen-gladpack.obj: gladpack.cpp
	source='gladpack.cpp' object='openscen-gladpack.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-gladpack.Po' tmpdepfile='$(DEPDIR)/openscen-gladpack.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-gladpack.obj `cygpath -w gladpack.cpp`

openscen-graphlib.o: graphlib.cpp
	source='graphlib.cpp' object='openscen-graphlib.o' libtool=no \
	depfile='$(DEPDIR)/openscen-graphlib.Po' tmpdepfile='$(DEPDIR)/openscen-graphlib.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-graphlib.o `test -f graphlib.cpp || echo '$(srcdir)/'`graphlib.cpp

openscen-graphlib.obj: graphlib.cpp
	source='graphlib.cpp' object='openscen-graphlib.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-graphlib.Po' tmpdepfile='$(DEPDIR)/openscen-graphlib.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-graphlib.obj `cygpath -w graphlib.cpp`

openscen-guy.o: guy.cpp
	source='guy.cpp' object='openscen-guy.o' libtool=no \
	depfile='$(DEPDIR)/openscen-guy.Po' tmpdepfile='$(DEPDIR)/openscen-guy.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-guy.o `test -f guy.cpp || echo '$(srcdir)/'`guy.cpp

openscen-guy.obj: guy.cpp
	source='guy.cpp' object='openscen-guy.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-guy.Po' tmpdepfile='$(DEPDIR)/openscen-guy.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-guy.obj `cygpath -w guy.cpp`

openscen-help.o: help.cpp
	source='help.cpp' object='openscen-help.o' libtool=no \
	depfile='$(DEPDIR)/openscen-help.Po' tmpdepfile='$(DEPDIR)/openscen-help.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-help.o `test -f help.cpp || echo '$(srcdir)/'`help.cpp

openscen-help.obj: help.cpp
	source='help.cpp' object='openscen-help.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-help.Po' tmpdepfile='$(DEPDIR)/openscen-help.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-help.obj `cygpath -w help.cpp`

openscen-input.o: input.cpp
	source='input.cpp' object='openscen-input.o' libtool=no \
	depfile='$(DEPDIR)/openscen-input.Po' tmpdepfile='$(DEPDIR)/openscen-input.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-input.o `test -f input.cpp || echo '$(srcdir)/'`input.cpp

openscen-input.obj: input.cpp
	source='input.cpp' object='openscen-input.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-input.Po' tmpdepfile='$(DEPDIR)/openscen-input.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-input.obj `cygpath -w input.cpp`

openscen-intro.o: intro.cpp
	source='intro.cpp' object='openscen-intro.o' libtool=no \
	depfile='$(DEPDIR)/openscen-intro.Po' tmpdepfile='$(DEPDIR)/openscen-intro.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-intro.o `test -f intro.cpp || echo '$(srcdir)/'`intro.cpp

openscen-intro.obj: intro.cpp
	source='intro.cpp' object='openscen-intro.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-intro.Po' tmpdepfile='$(DEPDIR)/openscen-intro.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-intro.obj `cygpath -w intro.cpp`

openscen-living.o: living.cpp
	source='living.cpp' object='openscen-living.o' libtool=no \
	depfile='$(DEPDIR)/openscen-living.Po' tmpdepfile='$(DEPDIR)/openscen-living.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-living.o `test -f living.cpp || echo '$(srcdir)/'`living.cpp

openscen-living.obj: living.cpp
	source='living.cpp' object='openscen-living.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-living.Po' tmpdepfile='$(DEPDIR)/openscen-living.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-living.obj `cygpath -w living.cpp`

openscen-loader.o: loader.cpp
	source='loader.cpp' object='openscen-loader.o' libtool=no \
	depfile='$(DEPDIR)/openscen-loader.Po' tmpdepfile='$(DEPDIR)/openscen-loader.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-loader.o `test -f loader.cpp || echo '$(srcdir)/'`loader.cpp

openscen-loader.obj: loader.cpp
	source='loader.cpp' object='openscen-loader.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-loader.Po' tmpdepfile='$(DEPDIR)/openscen-loader.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-loader.obj `cygpath -w loader.cpp`

openscen-obmap.o: obmap.cpp
	source='obmap.cpp' object='openscen-obmap.o' libtool=no \
	depfile='$(DEPDIR)/openscen-obmap.Po' tmpdepfile='$(DEPDIR)/openscen-obmap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-obmap.o `test -f obmap.cpp || echo '$(srcdir)/'`obmap.cpp

openscen-obmap.obj: obmap.cpp
	source='obmap.cpp' object='openscen-obmap.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-obmap.Po' tmpdepfile='$(DEPDIR)/openscen-obmap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-obmap.obj `cygpath -w obmap.cpp`

openscen-pal32.o: pal32.cpp
	source='pal32.cpp' object='openscen-pal32.o' libtool=no \
	depfile='$(DEPDIR)/openscen-pal32.Po' tmpdepfile='$(DEPDIR)/openscen-pal32.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-pal32.o `test -f pal32.cpp || echo '$(srcdir)/'`pal32.cpp

openscen-pal32.obj: pal32.cpp
	source='pal32.cpp' object='openscen-pal32.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-pal32.Po' tmpdepfile='$(DEPDIR)/openscen-pal32.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-pal32.obj `cygpath -w pal32.cpp`

openscen-parser.o: parser.cpp
	source='parser.cpp' object='openscen-parser.o' libtool=no \
	depfile='$(DEPDIR)/openscen-parser.Po' tmpdepfile='$(DEPDIR)/openscen-parser.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-parser.o `test -f parser.cpp || echo '$(srcdir)/'`parser.cpp

openscen-parser.obj: parser.cpp
	source='parser.cpp' object='openscen-parser.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-parser.Po' tmpdepfile='$(DEPDIR)/openscen-parser.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-parser.obj `cygpath -w parser.cpp`

openscen-pixie.o: pixie.cpp
	source='pixie.cpp' object='openscen-pixie.o' libtool=no \
	depfile='$(DEPDIR)/openscen-pixie.Po' tmpdepfile='$(DEPDIR)/openscen-pixie.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-pixie.o `test -f pixie.cpp || echo '$(srcdir)/'`pixie.cpp

openscen-pixie.obj: pixie.cpp
	source='pixie.cpp' object='openscen-pixie.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-pixie.Po' tmpdepfile='$(DEPDIR)/openscen-pixie.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-pixie.obj `cygpath -w pixie.cpp`

openscen-pixien.o: pixien.cpp
	source='pixien.cpp' object='openscen-pixien.o' libtool=no \
	depfile='$(DEPDIR)/openscen-pixien.Po' tmpdepfile='$(DEPDIR)/openscen-pixien.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-pixien.o `test -f pixien.cpp || echo '$(srcdir)/'`pixien.cpp

openscen-pixien.obj: pixien.cpp
	source='pixien.cpp' object='openscen-pixien.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-pixien.Po' tmpdepfile='$(DEPDIR)/openscen-pixien.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-pixien.obj `cygpath -w pixien.cpp`

openscen-radar.o: radar.cpp
	source='radar.cpp' object='openscen-radar.o' libtool=no \
	depfile='$(DEPDIR)/openscen-radar.Po' tmpdepfile='$(DEPDIR)/openscen-radar.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-radar.o `test -f radar.cpp || echo '$(srcdir)/'`radar.cpp

openscen-radar.obj: radar.cpp
	source='radar.cpp' object='openscen-radar.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-radar.Po' tmpdepfile='$(DEPDIR)/openscen-radar.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-radar.obj `cygpath -w radar.cpp`

openscen-screen.o: screen.cpp
	source='screen.cpp' object='openscen-screen.o' libtool=no \
	depfile='$(DEPDIR)/openscen-screen.Po' tmpdepfile='$(DEPDIR)/openscen-screen.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-screen.o `test -f screen.cpp || echo '$(srcdir)/'`screen.cpp

openscen-screen.obj: screen.cpp
	source='screen.cpp' object='openscen-screen.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-screen.Po' tmpdepfile='$(DEPDIR)/openscen-screen.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-screen.obj `cygpath -w screen.cpp`

openscen-smooth.o: smooth.cpp
	source='smooth.cpp' object='openscen-smooth.o' libtool=no \
	depfile='$(DEPDIR)/openscen-smooth.Po' tmpdepfile='$(DEPDIR)/openscen-smooth.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-smooth.o `test -f smooth.cpp || echo '$(srcdir)/'`smooth.cpp

openscen-smooth.obj: smooth.cpp
	source='smooth.cpp' object='openscen-smooth.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-smooth.Po' tmpdepfile='$(DEPDIR)/openscen-smooth.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-smooth.obj `cygpath -w smooth.cpp`

openscen-sound.o: sound.cpp
	source='sound.cpp' object='openscen-sound.o' libtool=no \
	depfile='$(DEPDIR)/openscen-sound.Po' tmpdepfile='$(DEPDIR)/openscen-sound.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-sound.o `test -f sound.cpp || echo '$(srcdir)/'`sound.cpp

openscen-sound.obj: sound.cpp
	source='sound.cpp' object='openscen-sound.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-sound.Po' tmpdepfile='$(DEPDIR)/openscen-sound.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-sound.obj `cygpath -w sound.cpp`

openscen-stats.o: stats.cpp
	source='stats.cpp' object='openscen-stats.o' libtool=no \
	depfile='$(DEPDIR)/openscen-stats.Po' tmpdepfile='$(DEPDIR)/openscen-stats.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-stats.o `test -f stats.cpp || echo '$(srcdir)/'`stats.cpp

openscen-stats.obj: stats.cpp
	source='stats.cpp' object='openscen-stats.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-stats.Po' tmpdepfile='$(DEPDIR)/openscen-stats.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-stats.obj `cygpath -w stats.cpp`

openscen-text.o: text.cpp
	source='text.cpp' object='openscen-text.o' libtool=no \
	depfile='$(DEPDIR)/openscen-text.Po' tmpdepfile='$(DEPDIR)/openscen-text.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-text.o `test -f text.cpp || echo '$(srcdir)/'`text.cpp

openscen-text.obj: text.cpp
	source='text.cpp' object='openscen-text.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-text.Po' tmpdepfile='$(DEPDIR)/openscen-text.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-text.obj `cygpath -w text.cpp`

openscen-treasure.o: treasure.cpp
	source='treasure.cpp' object='openscen-treasure.o' libtool=no \
	depfile='$(DEPDIR)/openscen-treasure.Po' tmpdepfile='$(DEPDIR)/openscen-treasure.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-treasure.o `test -f treasure.cpp || echo '$(srcdir)/'`treasure.cpp

openscen-treasure.obj: treasure.cpp
	source='treasure.cpp' object='openscen-treasure.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-treasure.Po' tmpdepfile='$(DEPDIR)/openscen-treasure.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-treasure.obj `cygpath -w treasure.cpp`

openscen-video.o: video.cpp
	source='video.cpp' object='openscen-video.o' libtool=no \
	depfile='$(DEPDIR)/openscen-video.Po' tmpdepfile='$(DEPDIR)/openscen-video.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-video.o `test -f video.cpp || echo '$(srcdir)/'`video.cpp

openscen-video.obj: video.cpp
	source='video.cpp' object='openscen-video.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-video.Po' tmpdepfile='$(DEPDIR)/openscen-video.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-video.obj `cygpath -w video.cpp`

openscen-view.o: view.cpp
	source='view.cpp' object='openscen-view.o' libtool=no \
	depfile='$(DEPDIR)/openscen-view.Po' tmpdepfile='$(DEPDIR)/openscen-view.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-view.o `test -f view.cpp || echo '$(srcdir)/'`view.cpp

openscen-view.obj: view.cpp
	source='view.cpp' object='openscen-view.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-view.Po' tmpdepfile='$(DEPDIR)/openscen-view.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-view.obj `cygpath -w view.cpp`

openscen-walker.o: walker.cpp
	source='walker.cpp' object='openscen-walker.o' libtool=no \
	depfile='$(DEPDIR)/openscen-walker.Po' tmpdepfile='$(DEPDIR)/openscen-walker.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-walker.o `test -f walker.cpp || echo '$(srcdir)/'`walker.cpp

openscen-walker.obj: walker.cpp
	source='walker.cpp' object='openscen-walker.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-walker.Po' tmpdepfile='$(DEPDIR)/openscen-walker.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-walker.obj `cygpath -w walker.cpp`

openscen-weap.o: weap.cpp
	source='weap.cpp' object='openscen-weap.o' libtool=no \
	depfile='$(DEPDIR)/openscen-weap.Po' tmpdepfile='$(DEPDIR)/openscen-weap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-weap.o `test -f weap.cpp || echo '$(srcdir)/'`weap.cpp

openscen-weap.obj: weap.cpp
	source='weap.cpp' object='openscen-weap.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-weap.Po' tmpdepfile='$(DEPDIR)/openscen-weap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-weap.obj `cygpath -w weap.cpp`

openscen-sai2x.o: sai2x.cpp
	source='sai2x.cpp' object='openscen-sai2x.o' libtool=no \
	depfile='$(DEPDIR)/openscen-sai2x.Po' tmpdepfile='$(DEPDIR)/openscen-sai2x.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-sai2x.o `test -f sai2x.cpp || echo '$(srcdir)/'`sai2x.cpp

openscen-sai2x.obj: sai2x.cpp
	source='sai2x.cpp' object='openscen-sai2x.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-sai2x.Po' tmpdepfile='$(DEPDIR)/openscen-sai2x.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-sai2x.obj `cygpath -w sai2x.cpp`

openscen-util.o: util.cpp
	source='util.cpp' object='openscen-util.o' libtool=no \
	depfile='$(DEPDIR)/openscen-util.Po' tmpdepfile='$(DEPDIR)/openscen-util.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-util.o `test -f util.cpp || echo '$(srcdir)/'`util.cpp

openscen-util.obj: util.cpp
	source='util.cpp' object='openscen-util.obj' libtool=no \
	depfile='$(DEPDIR)/openscen-util.Po' tmpdepfile='$(DEPDIR)/openscen-util.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(openscen_CXXFLAGS) $(CXXFLAGS) -c -o openscen-util.obj `cygpath -w util.cpp`
CXXDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)config.h.in$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags config.h.in $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic distclean distclean-compile distclean-depend \
	distclean-generic distclean-hdr distclean-tags distdir dvi \
	dvi-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-exec install-exec-am \
	install-info install-info-am install-man install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
